services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - firewall_service
      - health_service
      - notes_service

  auth_service:
    build:
      context: .
      target: auth_service
    ports:
      - "3003:3000"
    environment:
      - DATABASE_PATH=/data/auth.db
      - PRIVATE_KEY_PATH=/secrets/private.pem
      - PUBLIC_KEY_PATH=/secrets/public.pem
    volumes:
      - ./data/auth.db:/data/auth.db
      - ./private.pem:/secrets/private.pem:ro
      - ./public.pem:/secrets/public.pem:ro
    labels:
      - "mesh1.proxy.enable=true"
      - "mesh1.proxy.port=3000"
      - "mesh1.proxy.spec_path=/api/v1/api-docs/openapi.json"

  health_service:
    build:
      context: .
      target: health_service
    ports:
      - "3002:3002"
    environment:
      - HEALTH_CONFIG_PATH=/state/services.json
      - HEALTH_PORT=3002
    volumes:
      - ./services.json:/state/services.json:ro
    labels:
      - "mesh1.proxy.enable=true"
      - "mesh1.proxy.port=3002"
      - "mesh1.proxy.spec_path=/api/v1/api-docs/openapi.json"

  firewall_service:
    build:
      context: .
      target: firewall_service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_PATH=/data/firewall.db
      - PUBLIC_KEY_PATH=/secrets/public.pem
      - FIREWALL_BACKEND=mock
    volumes:
      - ./data/firewall.db:/data/firewall.db
      - ./public.pem:/secrets/public.pem:ro
    labels:
      - "mesh1.proxy.enable=true"                  # REQUIRED: Enables discovery
      - "mesh1.proxy.port=3001"                    # Internal port (default: 3000)
      - "mesh1.proxy.spec_path=/api/v1/api-docs/openapi.json" # Path to JSON spec (default: /api-docs/openapi.json)

  notes_service:
    build:
      context: .
      target: notes_service
    ports:
      - "3000:3003"
    environment:
      - DATABASE_PATH=/data/notes.db
      - PUBLIC_KEY_PATH=/secrets/public.pem
      - LISTEN_PORT=3003
    volumes:
      - ./data/notes.db:/data/notes.db
      - ./public.pem:/secrets/public.pem:ro
    labels:
      - "mesh1.proxy.enable=true"
      - "mesh1.proxy.port=3003"
      - "mesh1.proxy.spec_path=/api/v1/api-docs/openapi.json"

