version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    cap_add:
      - NET_ADMIN
    environment:
      - JWT_SECRET=SuperSecretValue
      - FIREWALL_BACKEND=nftables
      - DATABASE_PATH=/app/application.db
    volumes:
      - ./application.db:/app/application.db
