[package]
name = "auth_service"
version = "0.2.0-snapshot"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
axum = "0.8.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros"] }
async-trait = "0.1.89"
bcrypt = "0.18.0"
rand = "0.10.0"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
hex = "0.4.3"
sha2 = "0.10.9"
chrono = "0.4.43"
tower_governor = "0.8.0"
tracing = "0.1"

[dev-dependencies]
mockall = "0.14.0"
rsa = "0.10.0-rc.15"
tower = { version = "0.5.3", features = ["util"] }
http = "1.4.0"